// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RestfulApiTry.Persistence.Migrations
{
    [DbContext(typeof(RentDbContext))]
    [Migration("20250526075039_ChangedForeignKeyInFlatsConfiguration")]
    partial class ChangedForeignKeyInFlatsConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestfulApiTry.Persistence.Models.FlatModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageMark")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("CostPerDay")
                        .HasPrecision(7, 3)
                        .HasColumnType("decimal(7,3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsBathRoomAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWiFiAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int");

                    b.Property<short>("NumberOfFloors")
                        .HasColumnType("smallint");

                    b.Property<short>("NumberOfRooms")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("LandlordId");

                    b.ToTable("Flats");
                });

            modelBuilder.Entity("RestfulApiTry.Persistence.Models.LandlordInformationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Score")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("LandlordId")
                        .IsUnique();

                    b.ToTable("LandlordInformations");
                });

            modelBuilder.Entity("RestfulApiTry.Persistence.Models.LandlordModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LandlordInformationId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Landlords");
                });

            modelBuilder.Entity("RestfulApiTry.Persistence.Models.LesseeInformationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("LesseeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Score")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("LesseeId")
                        .IsUnique();

                    b.ToTable("LesseeInformations");
                });

            modelBuilder.Entity("RestfulApiTry.Persistence.Models.LesseeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LesseeInformationId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lessees");
                });

            modelBuilder.Entity("RestfulApiTry.Persistence.Models.FlatModel", b =>
                {
                    b.HasOne("RestfulApiTry.Persistence.Models.LandlordModel", "LandlordModel")
                        .WithMany("Flats")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandlordModel");
                });

            modelBuilder.Entity("RestfulApiTry.Persistence.Models.LandlordInformationModel", b =>
                {
                    b.HasOne("RestfulApiTry.Persistence.Models.LandlordModel", "LandlordModel")
                        .WithOne("LandlordInformationModel")
                        .HasForeignKey("RestfulApiTry.Persistence.Models.LandlordInformationModel", "LandlordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandlordModel");
                });

            modelBuilder.Entity("RestfulApiTry.Persistence.Models.LesseeInformationModel", b =>
                {
                    b.HasOne("RestfulApiTry.Persistence.Models.LesseeModel", "LesseeModel")
                        .WithOne("LesseeInformationModel")
                        .HasForeignKey("RestfulApiTry.Persistence.Models.LesseeInformationModel", "LesseeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LesseeModel");
                });

            modelBuilder.Entity("RestfulApiTry.Persistence.Models.LandlordModel", b =>
                {
                    b.Navigation("Flats");

                    b.Navigation("LandlordInformationModel");
                });

            modelBuilder.Entity("RestfulApiTry.Persistence.Models.LesseeModel", b =>
                {
                    b.Navigation("LesseeInformationModel")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
